run:
  skip-dirs:
    - book/2.1
    - book/2.2
    - book/2.3

linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - Printf
          - Sprintf
          - Fprintf
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: main-redeclared
        disabled: true

linters:
  enable:
    - govet
    - revive 